[ADD] solo stumper 2

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,6 +1,6 @@
 name: chocolatine
 
-on: [push, pull]:
+on: [push, pull_request]
   branches:
     - '**'
     - '!ga-ignore'
@@ -10,18 +10,18 @@ on: [push, pull]:
 
 jobs:
   check-repository-cleanliness:
-    runs-on: [ubuntu-latest]
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
-        - ref: [main]
+          -ref: main
       - uses: actions/check-repository-cleanliness@v1
         with:
-        - path: '.'
-        - run: var=0; for i in $(find -name "*.o" -o -name "*.a" -o -name "*.gcda" -o -name "*.gcno" -o -name "*.so" -o -name "*.gcov" -o -iname "*pain_au_chocolat*" -o -name "\#*\#" -o -name "*~" -o -path '*/tmp/*' -type f); do echo "::error file=$line,line=1::Unwanted file detected $i"; var=1; done; exit $var
-  
+          path: '.'
+        run: var=0; for i in $(find -name "*.o" -o -name "*.a" -o -name "*.gcda" -o -name "*.gcno" -o -name "*.so" -o -name "*.gcov" -o -iname "*pain_au_chocolat*" -o -name "\#*\#" -o -name "*~" -o -path '*/tmp/*' -type f); do echo "::error file=$line,line=1::Unwanted file detected $i"; var=1; done; exit $var
+
   check-program-compilation:
-    runs-on: [ubuntu-latest]
+    runs-on: ubuntu-latest
     timeout-minutes: 2
     container: epitechcontent/epitest-docker
     steps:
@@ -35,7 +35,7 @@ jobs:
         run: make fclean
 
   run_tests:
-    runs-on: [ubuntu-latest]
+    runs-on: ubuntu-latest
     timeout-minutes: 2
     container: epitechcontent/epitest-docker
     steps:
